### ISSUE TITLE
Change node value

### ISSUE THREAD

**Issue by laibulle** [ninjasphere/go-openzwave#6]
Hello, 

and thank you for this library. 

I am trying to control a Zwave dimmer with go-openzwave. But I have some troubles to understand some concept of the library.
1. Once I have stored all nodes in memory and NT.ALL_NODES_QUERIED is raised. How can I change node value since value struct is not exported and only Value interface is ?
2. What  is the difference between EventCallback and NotificationCallback ?
3. Should I deal with Device struct or Node ?

I am actually not really familiar with ZWave and it is maybe my main trouble. I have read some documentation from OpenZwave project but it didn't really help me for these questions.

Thank you

**Comment by jonseymour** [comment]
The Value interface has various Set methods which you can use to change the values.

The NotificationCallback exposes notifications generated by the OpenZWave library early in the notification life cycle. It is primarily used for debugging purposes and isn't really intended for any other use.

The EventCallback is used for announcing the availability of a node, a change to a node and the unavailability of a node. The key thing about the event call backs is that they are called after the device factory has been called to associate a device instance with a node. 

The device factory is where you create an application level abstraction of the underlying zwave device. Your application would interact with that abstraction, the implementation of which translates the actions into appropriate manipulations of the corresponding ZWave Nodes and Values.

So, the first thing I would do is create a wrapper for your dimmer that implements the Device interface plus the interface you would like your dimmer to have. Then implement a DeviceFactory which creates an instance of your dimmer type when it receives a Node with the correct identifiers. Then implement an EventCallback that handles the various kinds of events such as NodeAvailable, NodeUnavailable and NodeChanged.

Your event callback might receive a NodeAvailable event, get the related node with GetNode(), get the related device with GetDevice(), check that it can be cast to your Dimmer type and then store the reference to the Dimmer object in a map of dimmers.

Note that this API hasn't seem much real world use. I did use it to develop a Ninja Sphere [adapter](https://github.com/ninjasphere/driver-go-zwave) for ZWave devices, but even that code hasn't really been used much in practice. Feel free to open issues or raise PRs if you need changes to the API to make it easier for you to use.

**Comment by laibulle** [comment]
Thank you for this explanations, it really helped me. 

I am now able to change value of my dimmer using this code:

```
// DeviceDimmer struct
type DeviceDimmer struct {
    Name string
    node openzwave.Node
}

// ChangeValue func
func (d *DeviceDimmer) ChangeValue(value float32) {
    currentValue := d.node.GetValue(38, 1, 0)
    currentValue.SetString(fmt.Sprintf("%v", value))
}
```

I found the correct value debugging the library. Is there a better way to do that ?

**Comment by jonseymour** [comment]
You can have a look at the config directory of the C++ openzwave project for XML descriptions of various devices. I currently don't do anything in go-openzwave to make that information available via the go API.

**Comment by shayne** [comment]
I too am looking to write out some home automation to replace Smartthings. I know you said it's not really for public use, but figured it's a good start.

Following your input above, I put together the following: https://github.com/shayne/zwave

Would appreciate any feedback as I start to build out this project. Thanks for putting this project together!

**Comment by laibulle** [comment]
If it can help someone I share my project. Which is inspired by [home assistant](https://home-assistant.io/) and offer a MQTT API to create plugins.

https://github.com/laibulle/pepper

**Comment by jonseymour** [comment]
Thank you for the project points @shayne and @laibulle. I'll close this issue now.
